Algoritmo "cilindro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/09/2025
Var
// Seção de Declarações das variáveis

r, a, areaBase, volume: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreva("Informe o raio (r): ")
leia(r)

escreva("Informe a altura (a): ")
leia(a)

areaBase <- 3.14159 * r * r
volume <- a * areaBase

 escreva("Área da base: ", areaBase)
 escreva("Volume do cilindro: ", volume)


Fimalgoritmo